env:
  global:
    - CC_TEST_REPORTER_ID: c160f6f1729bb88e0b34b95f02292fcc9622317cd77b840252462a996a5eb677
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
language: swift
xcode_workspace: swift-ui-base.xcworkspace
xcode_scheme: swift-ui-base
osx_image: xcode11.4
cache:
  - bundler
  - cocoapods
before_install:
  - pod repo update
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - bundle install
  - pod install
script:
  - set -o pipefail
  - xcodebuild -workspace swift-ui-base.xcworkspace -scheme swift-ui-base -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.3' build test | xcpretty --test --color
after_script:
  - slather coverage
  - ./cc-test-reporter after-build -t cobertura --exit-code $TRAVIS_TEST_RESULT
